//
// Generated file, do not edit! Created by opp_msgc 4.3 from applications/iec61850message.msg.
//

#ifndef _IEC61850MESSAGE_M_H_
#define _IEC61850MESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/iec61850message.msg</tt> by opp_msgc.
 * <pre>
 * packet Iec61850message {
 *     int vid;
 *     int priority;	
 *     int eType;
 *     int tci; 
 *     double timeStamp;
 * 	unsigned char content[]; 
 * }
 * </pre>
 */
class Iec61850message : public ::cPacket
{
  protected:
    int vid_var;
    int priority_var;
    int eType_var;
    int tci_var;
    double timeStamp_var;
    unsigned char *content_var; // array ptr
    unsigned int content_arraysize;

  private:
    void copy(const Iec61850message& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Iec61850message&);

  public:
    Iec61850message(const char *name=NULL, int kind=0);
    Iec61850message(const Iec61850message& other);
    virtual ~Iec61850message();
    Iec61850message& operator=(const Iec61850message& other);
    virtual Iec61850message *dup() const {return new Iec61850message(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getVid() const;
    virtual void setVid(int vid);
    virtual int getPriority() const;
    virtual void setPriority(int priority);
    virtual int getEType() const;
    virtual void setEType(int eType);
    virtual int getTci() const;
    virtual void setTci(int tci);
    virtual double getTimeStamp() const;
    virtual void setTimeStamp(double timeStamp);
    virtual void setContentArraySize(unsigned int size);
    virtual unsigned int getContentArraySize() const;
    virtual unsigned char getContent(unsigned int k) const;
    virtual void setContent(unsigned int k, unsigned char content);
};

inline void doPacking(cCommBuffer *b, Iec61850message& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Iec61850message& obj) {obj.parsimUnpack(b);}


#endif // _IEC61850MESSAGE_M_H_
